# Configurations de base
title: The Architect
description: Modern cloud, data, and AI architecture
baseurl: ""
url: "http://localhost:4000"

# Configuration du serveur
host: 0.0.0.0
port: 4000
livereload: true
livereload_port: 35729

# Configuration de la compilation
incremental: true
strict_front_matter: true

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git

#about: "Bootstrap theme for jekyll"
markdown: kramdown
kramdown:
    math_engine: katex
#permalink: /:categories/:title/
permalink: pretty
disqus_short_name: thearchitect-page-disqus-com

plugins: 
  - jekyll-paginate
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  
paginate_path: "/page:num/"

paginate: 4


main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
