title: ""

#about: "Bootstrap theme for jekyll"
markdown: kramdown
#permalink: /:categories/:title/
permalink: pretty
url: ""
baseurl: ""
disqus_short_name: thearchitect-page-disqus-com

plugins: 
  - jekyll-paginate
  - jemoji
  
paginate_path: "/page:num/"

paginate: 4


main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
